name: Create PR to main on Deploy Label

on:
  pull_request:
    types:
      - closed

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged and has deploy label
        id: check-conditions
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" && $(jq -r '.labels[].name' <<< "${{ github.event.pull_request.labels }}" | grep -q 'deploy') ]]; then
            echo "::set-output name=create_pr::true"
          else
            echo "::set-output name=create_pr::false"
          fi

      - name: Create PR to main
        if: steps.check-conditions.outputs.create_pr == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin main:main
          git checkout -b deploy-branch
          git merge main --no-commit --no-ff
          git commit -m "Merge main into deploy branch"
          git push origin deploy-branch
          gh pr create --base main --head deploy-branch --title "Merge develop into main" --body "This pull request was automatically created when a PR was merged into develop with the 'deploy' label."
