
name: Run Tests on Label

on:
  pull_request:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'attack')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'yashkumarverma-fampay/temp'
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure you have the correct access rights

      - name: Run test.sh
        run: |
          chmod +x ./test.sh
          ./test.sh
