name: Create PR to Master on Deploy Label

on:
  pull_request:
    types:
      - closed

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged and has deploy label
        id: check-conditions
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' && ${{ github.event.pull_request.merged }} == 'true' && $(jq -r '.labels[].name' <<< "${{ github.event.pull_request.labels }}" | grep -q 'deploy') ]]; then
            echo "::set-output name=create_pr::true"
          else
            echo "::set-output name=create_pr::false"
          fi

      - name: Create PR to Master
        if: steps.check-conditions.outputs.create_pr == 'true'
        run: |
          git checkout master
          git pull origin master
          git checkout -b update-master
          git merge develop --no-ff -m "Merge develop into master"
          git push origin update-master
          gh pr create --base master --head update-master --title "Merge develop into master" --body "This pull request was automatically created when a PR was merged into develop with the 'deploy' label."
