name: Create PR to Master on Deploy Label

on:
  pull_request:
    types:
      - closed

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is merged and has deploy label
        id: check-conditions
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' && ${{ github.event.pull_request.merged }} == 'true' && $(jq -r '.labels[].name' <<< "${{ github.event.pull_request.labels }}" | grep -q 'deploy') ]]; then
            echo "::set-output name=create_pr::true"
          else
            echo "::set-output name=create_pr::false"
          fi

      - name: Create PR to Master
        if: steps.check-conditions.outputs.create_pr == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin master:master
          git checkout -b deploy-branch
          git merge master --no-commit --no-ff
          git commit -m "Merge master into deploy branch"
          git push origin deploy-branch
          gh pr create --base master --head deploy-branch --title "Merge develop into master" --body "This pull request was automatically created when a PR was merged into develop with the 'deploy' label."

